### ISSUE TITLE
N00b Question

### ISSUE THREAD

**Issue by TechGuyTN** [direct-connect/go-dcpp#100]
How do I run private only allowing registered users to view files? Also is there a command list? I was able to create a user and login to my hub, am I able to add users and do other tasks via the client? cli on host machine? A bit confused. Thanks in advance.

**Comment by dennwc** [comment]
Sorry for the late response, I missed the issue notification somehow.

There is no option for now to allow only registered users. But it's a one line fix, so can be added easily.

We don't have a documentation page for commands, but you can send a `!help` (or just `!h`) command in the chat to get the list of commands. You may also find it in the code [here](https://github.com/direct-connect/go-dcpp/blob/master/hub/cmds.go#L58).

Hmm, I don't think we have any command to register user from the hub. But it's also an easy fix, we should definitely add it. As a temporary workaround you can shutdown the hub, add users via command line and run it again. I know it's not a satisfying way to add users, but for now we were more focused on public hubs where users can self-register.

**Comment by dennwc** [comment]
Created #102 and #103 to track this.

**Comment by TechGuyTN** [comment]
Just seeing this, thank you for explaining and I understand 100%. Thank you for your time & development :)
