### ISSUE TITLE
Build on windows fails

### ISSUE THREAD

**Issue by HadesDCH** [direct-connect/go-dcpp#109]
C:\>cd go

C:\Go>go build .\cmd\go-hub
go: finding github.com/direct-connect/go-dcpp/internal/safe latest
go: finding github.com/direct-connect/go-dcpp/version latest
go: finding github.com/direct-connect/go-dcpp/internal latest
go: finding github.com/direct-connect/go-dcpp/nmdc/client latest
go: finding github.com/direct-connect/go-dcpp/nmdc latest
build github.com/direct-connect/go-dcpp/cmd/go-hub: cannot load github.com/direct-connect/go-dcpp/internal/safe: no matching versions for query "latest"

**Comment by dennwc** [comment]
@HadesDCH Can you please provide an output for those two commands?
```
go version
go env
```

**Comment by HadesDCH** [comment]
C:\Users\Administrator>go version
go version **go1.13.4** windows/amd64

C:\Users\Administrator>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build206042838=/tmp/go-build -gno-record-gcc-switches

**Comment by dennwc** [comment]
OK, this is exactly what I've expected: your Go compiler is installed into `C:\Go`. This means that the source code for the hub must be in any other directory except the `C:\Go`. Try moving it to `C:\GoProjects\go-dcpp`, for example.

**Comment by HadesDCH** [comment]
Ok will try this and close this issue once resolved or update. Will be in some hours as i got to leave r now.
Thank You.

**Comment by HadesDCH** [comment]
OK.
So i didn't move anything but new updates fix this issue. Even with project inside c:/go. So i'm closing this.
Thanx!
