### ISSUE TITLE
Respect the hublist XSD for an output

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#26]
For https://github.com/direct-connect/go-dcpp/tree/master/cmd/dcping:

Can you implement an output that respect this XSD: https://gitlab.com/dcnf/hublist/blob/master/hublist.xml.xsd

Thank you in advance

**Comment by dennwc** [comment]
Fixed in https://github.com/direct-connect/go-dcpp/commit/26e98d88f677a54ff024845beb47ba184a671085
