### ISSUE TITLE
Give a shorter version for encoding

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#31]
What I have:
```
# /root/go-dcpp/dcping ping "dchub://XXXXXXX:421" --out=xml
<Hub Name="Yeah-Hub" Address="dchub://XXXXXXX:421" Encoding="WINDOWS-1250" Shared="142122682261" Software="Verlihub" Status="Online" Users="8"></Hub>
```

What I would like to have:
```
# /root/go-dcpp/dcping ping "dchub://XXXXXXX:421" --out=xml
<Hub Name="Yeah-Hub" Address="dchub://XXXXXXX:421" Encoding="CP1250" Shared="142122682261" Software="Verlihub" Status="Online" Users="8"></Hub>
```

Is it possible to do that at your side?
Thanks in advance

**Comment by dennwc** [comment]
The encoding field follows [W3C recommendation](https://www.w3.org/TR/encoding/), but you are right, I can convert them for XML output so it will be more compatible with existing implementations.

**Comment by Kcchouette** [comment]
Like you want. I can do it on my side if you do not want to change it :stuck_out_tongue_winking_eye:
