### ISSUE TITLE
Encoding problem of name

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#33]
As you may know, unicode should be accepted in name (and even in URL but it's not the subject here).
Some name is writen in cyrilic: `ðàäóæíûé ãåé-õàá`.
But the pinger failed to treat it:
```
# /root/go-dcpp/dcping ping "dchub://XXXX.ru:411"
2019/03/04 22:06:09 invalid characters in name: "\xa0\xf0\xe0\xe4\xf3\xe6\xed\xfb\xe9\xa0\xe3\xe5\xe9-\xf5\xe0\xe1"
{"addr":["dchub://XXXX.ru:411"],"status":"offline"}*
```

**Comment by Kcchouette** [comment]
Moreover, some names are just `<Enter hub name here>`, eg a correct name

**Comment by dennwc** [comment]
I need to know more about this hub. Does it report any specific encoding to the pinger? Because if not, we have no way to detect it.

In any case, the pinger should not fail that way on encoding errors.

**Comment by Kcchouette** [comment]
> Does it report any specific encoding to the pinger?

I think we misunderstand.

Here, the case is, the hub is named "ðàäóæíûé ãåé-õàá" in other hublist.
When pinging it using dcping : `/root/go-dcpp/dcping ping "dchub://XXXX.ru:411"`
The pinger returns the error: `invalid characters in name: "\xa0\xf0\xe0\xe4\xf3\xe6\xed\xfb\xe9\xa0\xe3\xe5\xe9-\xf5\xe0\xe1"`

After some research, (for eg https://www.online-toolz.com/tools/text-unicode-entities-convertor.php /  Decode/Unescape Unicode Entities) `\xa0\xf0\xe0\xe4\xf3\xe6\xed\xfb\xe9\xa0\xe3\xe5\xe9-\xf5\xe0\xe1` = ` ðàäóæíûé ãåé-õàá`

This problem occurs in this case: `invalid characters in name: "<Enter hub name here>"` (dchub://137.74.198.217:1209 or dchub://94.23.195.217:1209)

**Comment by dennwc** [comment]
OK, thanks for clarifying it!

**Comment by Kcchouette** [comment]
The first case (`invalid characters in name: "\xa0\xf0\xe0\xe4\xf3\xe6\xed\xfb\xe9\xa0\xe3\xe5\xe9-\xf5\xe0\xe1"`) is from dchub://hubqueers.ru:411
