### ISSUE TITLE
Unknow errors

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#34]
Hello,

Here a general garbage issue as I don't know how to report it to you, but theses errors exists.

While pinging a hub, I sometimes have from it:
- `2019/03/04 22:17:26 text is too long` and so it put it as offline
- `2019/03/04 22:21:40 connection closed: ������ ��� �������� ���� ��� ������������� ������������ ������� Lama: http://XXXX.tv/
{"addr":["dchub://hub.XXXX.tv:2223"],"status":"offline"}` → in this case, I think it should be declared as online
- same goes for `2019/03/04 22:23:56 connection closed: Too few slots open, you have: 1, minimum for your profile is: 2 {"addr":["dchub://XXXX.no-ip.org:412"],"status":"offline"}`
- same for `2019/03/04 22:25:49 unknown field before connection P {"addr":["dchub://XXXXX.servebeer.com:2007"],"status":"offline"}` (and maybe you know how to deal for connection P; sometimes it's `unknown field before connection A`)
- `2019/03/04 22:28:26 hub info contain: 12 parameters {"addr":["dchub://XXXX.ddns.net:8000"],"status":"offline"}`
- `2019/03/04 22:29:37 invalid raw user command
{"addr":["dchub://XXXX.no-ip.org:1444"],"status":"offline"}`
- `2019/03/04 22:33:52 cannot read chat message: value is too large {"addr":["dchub://XXX.sytes.net:444"],"status":"offline"}`
- `2019/03/04 22:34:39 strconv.ParseUint: parsing "BOT": invalid syntax
{"addr":["dchub://web.XXXX.ru:411"],"status":"offline"}`
- `2019/03/04 22:35:33 unexpected EOF {"addr":["dchub://ordinary.XXXX.pl:1111"],"status":"offline"}`

**Comment by dennwc** [comment]
Awesome, thanks for the report! I'm closing this issue for a bunch of more specific ones.
