### ISSUE TITLE
Pinger: unexpected EOF

### ISSUE THREAD

**Issue by dennwc** [direct-connect/go-dcpp#42]
It may or may not be an issue, but we got `unexpected EOF` for `dchub://ordinary.XXXX.pl:1111`. It may be the hub dropping the connection, or pinger misinterpreting the connection close event.

Related to #34

**Comment by dennwc** [comment]
Cannot reproduce. Seems to be a connection failure.

**Comment by Kcchouette** [comment]
Reproduced with "dchub://ordinary.dchub.pl:1111"

**Comment by dennwc** [comment]
Sorry, but I still cannot reproduce an issue. Can you please provide a log from the pinger when running with `--debug`?

**Comment by Kcchouette** [comment]
I'll test later with new version but I think last version fix it.

**Comment by Kcchouette** [comment]
It's fixed on new version
