### ISSUE TITLE
Ping: Encoding issue

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#64]
Maybe it's related to CP encoding of hub, but:
```
./dcping ping "dchub://novosibirsk-forever.ru:41
"{"name":"*������������-�Forever*","desc":"������������� ����.px.","addr":["dchub://novosibirsk-forever.ru:411","dchub://novosibirsk-foreverru:411"],"soft":{"name":"PtokaX","vers":"","ext":["NoHello","UserCommand","UserIP2","BotINFO","HubINFO"]},"users":3820,"share":2273176896936735}
```
`*������������-�Forever*` should be transcribe as `*Новосибирск - Forever*`

**Comment by dennwc** [comment]
This specific hub does not provide any encoding. I added an option (`--encoding` or `-e`) to specify the fallback encoding. So if you somehow know it up front, it will decode the info correctly.

**Comment by Kcchouette** [comment]
@dennwc to sum up: because that hub is not returning encoding in ping, you can't correctly fixed it?

**Comment by dennwc** [comment]
Correct, there is no good way to detect encoding automatically.

Agree, we should reach out either to hub owners, or hub developers. If developers are not active, hub owners may need to update to the latest version. Even if the latest version is not sending the encoding, there are still ways to work around it (place it to the hub description, etc). I will then reopen the issue to track this.

**Comment by Kcchouette** [comment]
To avoid all the issues about encoding, I'm using `--encoding` in all case:
https://github.com/DCNF/Hublist/commit/74d97d1c8944addf7eebf12fc01eebdb7fbbca4f

So I think you can close (if you think it's ok) this issue :)
Thanks

**Comment by dennwc** [comment]
Closing this, I don't think anything else can be done here. Reaching out to hub admins will be done separately.
