### ISSUE TITLE
Ping: have the hability to customize hub/slot number

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#69]
Related to #52 and  #68 

`connection closed: Error: Your DC++ tag is reporting less then 0 hubs or slots!`

**Comment by dennwc** [comment]
Sorry, but it appears that this cannot be fixed and this is an error in the hubsoft. The pinger advertises 5 slots, but this specific hub seems to fail to parse it for some reason.

I will leave it open in case we can get a log from another pinger that passes the validation for this hub.

**Comment by dennwc** [comment]
Also added the ability to specify all those parameters as command-line flags.

**Comment by Kcchouette** [comment]
> I will leave it open in case we can get a log from another pinger that passes the validation for this hub.

Good luck. New time I'll paste here hub addresses with details when they are concerned with this problem.
/me hoping it's not PtokaX

**Comment by Kcchouette** [comment]
Now that redirect is implemented, seems this bug is fixed.
Here the details: (and here before the redirect: https://github.com/DCNF/Hublist/wiki/Session-of-May-1rst-2019#connection-closed-error-your-dc-tag-is-reporting-less-then-0-hubs-or-slots)
```
$ ./dcping ping 'dchub://dc.pashahub.ru:411'
{"name":"Pasha Hub","addr":["dchub://dc.pashahub.ru:411"],"soft":{"name":"verlihub","vers":"v0.9.9a","ext":["OpPlus","NoGetINFO","NoHello","UserIP2","HubINFO","ZPipe"]},"users":0,"redirect":"piter.feardc.net"}
```
I'm letting you closing the issue
