### ISSUE TITLE
Have a different status than error for registered hub

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#70]
```
$ ./dcping ping "adc://thefreehub.sytes.net:888"
2019/03/12 20:27:34 code 26: Registered users only.
{"name":"[DK] [• The Free Hub •]","desc":"[DK] [• The Free Private Hub •]","addr":["adc://thefreehub.sytes.net:888"],"encoding":"utf-8","soft":{"name":"LUADCH","vers":"v2.19","ext":["OSNR","UCM0","UCMD","BAS0","BASE","TIGR","KEYP"]},"users":0,"status":"error"}
```

What I expect is to have another value different of error:
 - Online
 - Offline
 - Error (for errors of encoding, etc to be reported here)
 - Registered
 - etc…

**Comment by dennwc** [comment]
Added an `errcode` field to the JSON and `ErrCode` attribute to XML with an ADC error code if it's available. "Registered" corresponds to the `226` code.

This should help to account for all possible error codes.
