### ISSUE TITLE
Ping, nmdc: connection closed: This hub is running [...]

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#75]
```
 ./dcping ping "dchub://dc.sungate.su:411"
2019/03/14 19:04:18 connection closed: This hub is running SunGateDCH by Meloun v1.15
{"name":"SunGate DC++ Hub","addr":["dchub://dc.sungate.su:411"],"soft":{"name":"DCPLUSPLUS0.707ABCABC","ext":["NoGetINFO","NoHello","UserIP2","HubTopic","BotList","MCTo","ZPipe"]},"users":0,"status":"error"}
```

**Comment by dennwc** [comment]
Seems to be an issue with a hubsoft - it closes the connection right after sending the hub info. It happens before the user list, so we can't even get the user count.

The workaround is possible - the initial ping may fail and the pinger will retry the second time, this time pretending to be a real client.

**Comment by Kcchouette** [comment]
This hubsoft seems to have problem with other pinger as well: https://forum.dchublist.org/viewtopic.php?f=4&t=72

**Comment by RoLex** [comment]
this is exactly why my pinger collect user count from MyINFO rather than HubINFO 😄 hubs like YnHub and some others sometimes dont send HubINFO at all.

**Comment by dennwc** [comment]
Fixed in the latest version.
