### ISSUE TITLE
Ping, nmdc: connection closed: This hub is for registered users only

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#76]
```
./dcping ping "dchub://zebedee.loginto.me:32410"
2019/03/14 19:06:22 connection closed: This hub is for registered users only
{"name":" ","addr":["dchub://zebedee.loginto.me:32410","dchub://hublist.org.nz:413"],"soft":{"name":"MHWL","vers":"0.2","ext":["NoHello","NoGetINFO","TLS","UserIP2","UserCommand","TTHSearch","BotINFO","BotList","MCTo","GetZBlock","SaltPass","FailOver"]},"users":0,"status":"error"}
```

**Comment by Kcchouette** [comment]
@dennwc your commit seems a bit trash... Controlling the error return by your pinger to set the hub at private.
Does the private hub in nmdc not standard like in adc?

**Comment by dennwc** [comment]
Right, there is no standard error code or command to indicate this. So we will have to use the string matching. Even the spec [mentions](https://github.com/direct-connect/protocols/blob/master/nmdc/nmdc.md#status-messages) that status messages are represented by plain text messages and should be interpreted by matching the text.
