### ISSUE TITLE
NMDC searches always delivered as passive

### ISSUE THREAD

**Issue by gswly** [direct-connect/go-dcpp#80]
Hi, i was working on automated tests between dctk and go-dcpp, and i noticed that all NMDC search requests, active or passive, are transformed into passive ones, making validation impossible.

This behavior is also described in comments, but no reasons are provided:
https://github.com/direct-connect/go-dcpp/blob/1740f36f0478bac91162ab026246243a80759515/hub/hub_nmdc.go#L612

What's the reason of this choice?
If this is just a WIP i can write a patch that implements active searches.

Thanks

**Comment by dennwc** [comment]
This is intentional. Passive search is the only way to allow users from both protocols on the same hub to search reliably.

**Comment by gswly** [comment]
ok, thanks
