### ISSUE TITLE
ADC private messages forwarded as BMSG instead of DMSG

### ISSUE THREAD

**Issue by gswly** [direct-connect/go-dcpp#83]
Private messages are actually wrapped in a Broadcast-type frame:
https://github.com/direct-connect/go-dcpp/blob/8bc128e8f1def6e40b638c81e50d8f6c40d46af9/hub/hub_adc.go#L1052

In most hubs, private messages are wrapped in Direct-type frames. The specification does not directly address this point, but provides examples that show how public messages are sent via BMSG, and private messages via DMSG:
https://adc.dcbase.org/Protocol

Is there a specific reason for this choice? this discrepance was again reported by automated tests.
Thanks

**Comment by dennwc** [comment]
Definitely a bug, probably a type from a refactoring. Should definitely be fixed ASAP.
