### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by TechGuyTN** [direct-connect/go-dcpp#99]
Has anybody successfully configured with cloudflare yet? If so can you please point me in the direction of procedure? Thanks in advance :)

**Comment by dennwc** [comment]
Can you please elaborate? Do you want to use CloudFlare's DDoS protection with the hub?

**Comment by TechGuyTN** [comment]
I would like to hide ip of hub and also protect against ddos.

**Comment by dennwc** [comment]
I think this is the page you are looking for:
https://www.cloudflare.com/products/cloudflare-spectrum/

I can't give any more details though - it's not related to the hub itself, in fact. Any TCP proxy/protection service will work with it (but not HTTP/HTTPS!).

But feel free to reopen if you have any specific issues with it.
